#!/bin/bash

set -e

: ${GUI:="SSH"}
if [ "$GUI" = "VNC" ] ; then
  GUICMD="vnc=1 vncpassword=\"12345678\""
elif [ "$GUI" = "SSH" ] ; then
  GUICMD="ssh=1 ssh.password=\"12345678\""
else
  echo "Invalid GUI type: $GUI"
  exit 1
fi

: ${DOWNLOAD_BASE:="http://download.opensuse.org/distribution/leap/15.5/repo/oss/boot/x86_64/loader/"}

echo "####################################"
echo "# Install required packages to the #"
echo "# rescue system                    #"
echo "####################################"
echo

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install --assume-yes --show-progress kexec-tools aria2 btrfs-progs net-tools

echo "####################################"
echo "# Download installation system     #"
echo "####################################"
echo

wget --output-document=initrd.install ${DOWNLOAD_BASE}initrd
wget --output-document=vmlinuz.install ${DOWNLOAD_BASE}linux

echo "####################################"
echo "# Switching to installation system #"
echo "####################################"
echo

NETDEV=`ip -o route get to 1.1.1.1 | sed -n 's/.*dev \([a-z0-9.]\+\).*/\1/p'`
IP=`ip -o route get to 1.1.1.1 | sed -n 's/.*src \([0-9.]\+\).*/\1/p'`
GW=`ip -o route get to 1.1.1.1 | sed -n 's/.*via \([0-9.]\+\).*/\1/p'`
NETMASK=`ifconfig "$NETDEV" | awk '/netmask/{ print $4;}'`

COMMANDLINE="noapic $GUICMD install=http://download.opensuse.org/distribution/leap/15.5/repo/oss/ hostip=$IP netmask=$NETMASK gateway=$GW nameserver=1.1.1.1"

echo "Commandline for kexec: $COMMANDLINE"

kexec -l vmlinuz.install --initrd=initrd.install --command-line="$COMMANDLINE"


echo "####################################"
echo "# Ready                            #"
echo "####################################"
echo
echo "Everything set up, run the following command to switch to the installation system:"
echo "  kexec -e"
